name: My First Workflow
    
    on:
      push:
        branches: [ "main" ]
    
    jobs:
      greet:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
    
          - name: Say Hello
            run: echo "GitHub Actions is now running in your repo!"
          
          - name: List files
            run: ls -R
    
